#+title:  Hosting your Lab or Experiment with Virtual Labs 
#+Author: VLEAD
#+Email: engg@vlabs.ac.in
#+DATE: [2020-04-18 Sat]

* Virtual Labs Hosting Community
** Virtual-Labs community
[[https://vlab.co.in][Virtual Labs]] is a collection of online experiments in
science and engineering.  It is currently being funded by
the Govt. of India's Ministry of Human Resources and
Development.  

The labs are built by a large community of developers
organized under the Github oganization `[[https://github.com/virtual-labs][virtual-labs]]'.

** How do I become part of the virtual labs community?

Currently, only labs that have been developed using the
virtual labs development process being maintained at [[http://vlabs.iitb.ac.in/vlab/][IIT
Bombay]].

If you wish to be part of the development community, please
contact the virtual labs outreach (TODO: add link)

** The Engineer's Forum
The [[https://github.com/virtual-labs/engineers-forum][engineers-forum]] is a project under the [[https://github.com/virtual-labs][virtual-labs]]
organization.  It is the single-point place for registering
experiments and labs, and requesting their hosting under
[[https://github.com/virtual-labs][virtual-labs]]. 

** Who can register and request hosting?
To register an experiment with virtual-labs you need to have
the following

  1. A github username and profile.

  2. The profile should indicate your university college
     affiliation.  Your college should already be part of
     the virtual labs community.

  3. The profile should include an email. 

  4. The first time you register an experiment or lab, you
     may receive an email asking you to confirm your
     affiliation to the college and other bona fides.

If you are a team in a college working on virtual labs, we
suggest that you create a separate user id or create a team
under the [[https://github.com/virtual-labs][virtual-labs]] organization.

* Experiment 
An experiment is the basic hostable unit of Virtual Labs.
** Experiment Hosting life cycle
The experiment hosting life cycle consists of the following
types of events:

 1. Request to Register an experiment (one time)
 2. Request hosting (multiple times)
 3. Request update of experiment attributes (multiple times)
 4. Request deregistration of the experiment (one time)

Each request is filed as an [[https://github.com/virtual-labs/engineers-forum/issues/new/choose][issue]] on the [[https://github.com/virtual-labs/engineers-forum][engineers-forum]].

** Experiment Registration

   The registration of an experiment defines the experiment as
   a hostable entity and makes it available to the virtual-labs
   organization to host it.

   Information in the registration issue includes the
   following:

   1. Name of the Experiment

   2. The owners of the experiment (by default, at least the github
	  user-name filing the registration request).   

   3. The source code repository of the experiment.

** Identity  of an Experiment
   An experiment is identified by its registration issue id on
   [[https://gitlab.com/virtual-labs/engineers-forum]].  
   
** Owner(s) of an Experiment
   The github user-name(s) associated with the experiment.
   Only owners of an experiment may request issue requests
   relating to the hosting lifecycle of an experiment.

** Source repository (Repo) of an Experiment
   An experiment's source code resides in a repository.  The
   mapping of an experiment to its repository may be changed.

** Experiment (deployment) Descriptor
   An experiment's descriptor is in the file =descriptor.json=
   at the top-level of the experiment's repo. 

   The descriptor contains multiple fields.
   1. Name of the experiment
   2. Meta data
   3. Build paramaters (command, build directory, source
	  directory, software dependencies)

   A formal specification of the descriptor will be given
   presently. (TODO)



** Requesting the Hosting of an Experiment
   A hosting request ideally results in the experiment being
   hosted at a url on the virtual labs website
   (http://vlabs.ac.in).   

   The basic information needed for hosting is the following:

   1. *Experiment (Registration) Id*: #< -- put id here -- >
   2. *Git Tag*: <-- should be a valid git tag of the sources -->

   The workflow for hosting is described in the [[./hosting-process.org][hosting process]]
   document.

** Requesting a changing in the attributes of an experiment

Over time, an experiment's attributes, like sources
repository and owner's might change.  

This is done by raising an `Experiment Info Update' request
on the forum.  This request has the following fields.  It is
mandatory to fill the first field and at least one of the
remaining fields.

1. *Experiment Registration Id*: #<put issue id here>
2. *Revise Name of Experiment to*: 
3. *Add these users as owners*: [@user-id ...]
4. *Remove these existing owners*: [@user-id ...]
5. *Update experiment repo url to*: 

** Requesting the deregistration of an experiment
An experiment may be requested for deregistration if the
owner no longer wishes to have the experiment as part of the
virtual labs set of experiments.  A deregistered experiment
is presumably no longer maintained.

Since an experiment is shared across labs, deregistration
doesn't necessarily mean it will be disappear from the lab.
However, any lab containing a decegistered experiment will
come with a warning saying that that experiment may not be
reliably available anymore.

* Lab
A lab is an aggregate of experiments.  A lab is also the
basic unit of hosting.  A lab has its own source repository.
That repository may include experiments sources in it, or it
may be point to other experiment repositories.  This
facilitates sharing of experiments across labs.

** Lab Registration

   The registration of a lab defines the lab as a hostable
   entity and makes it available to the virtual-labs
   organization to host it.

   Information in the registration issue includes the
   following:

   1. Name of the Lab

   2. The owners of the lab (by default the github
	  user-name filing the registration request).   

   3. The source code repository (repo) of the lab.

** Identity  of a Lab
   An lab is identified by its registration issue id on
   [[https://gitlab.com/virtual-labs/engineers-forum][engineers-forum]].

** Owner(s) of a Lab
   The github user-name(s) associated with the experiment.
   Only owners of an experiment may request issue hosting
   requests.

** Source repository (Repo) of a Lab 
   An experiment's source code resides in a repository.  The
   mapping of an experiment to its repository may be changed.


** Types of labs

A lab is of two types:

  1. *Container*:  it merely holds together already existing
     experiments.   

  2. *Monolithic*: it contains the source code of all its
     experiments.  Experiments in a monolithic lab are not
     available for sharing by other labs. 

** Lab (deployment) Descriptor
   An experiment's descriptor is in the file =descriptor.json=
   at the top-level of the experiment's repo. 

   The descriptor contains multiple fields.
   1. Name of the Lab

   2. Meta data

   3. Whether this lab is a container or monolithic. 

   4. If the lab is a container, the list of id's of all its
      experiments.

   5. If the lab is monolithic, information about its build
      parameters (command, build directory, source
      directory, software dependencies, etc.)

A formal specification of the descriptor will be given
presently. (TODO)

** Requesting the Hosting of a Lab
   A hosting request ideally results in the lab being
   hosted at a url on the virtual labs website
   (http://vlabs.ac.in).   

   The basic information needed for hosting is the following:

   1. *Lab (Registration) Id*: #< -- put id here -- >
   2. *Git Tag*: <-- should be a valid git tag of the sources -->

   The workflow for hosting is described in the [[./hosting-process.org][hosting process]]
   document. 

** Requesting a change in the attributes of a Lab

Over time, a lab's attributes, like source repository and
owner's might change.

This is done by raising an `Lab Info Update' request on the
forum.  This request has the following fields.  It is
mandatory to fill the first field and at least one of the
remaining fields.

1. *Lab Registration Id*: #<put issue id here>
2. *Revise Name of Lab to*: 
3. *Add these users as owners*: [@user-id ...]
4. *Remove these existing owners*: [@user-id ...]
5. *Update lab repo url to*: 

** requesting the deregistration of a Lab
An lab may be requested for deregistration if its owner no
longer wishes to have the lab as part of the hosted virtual
labs offerings.  A deregistered lab is presumably no longer
maintained and will be flagged as `no longer maintained' on
the main [[http:vlab.co.in][virtual labs landing page]].




